### PR TITLE
Refreshed harbour-jtox-es.ts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by almindor** [comment]
Hey, could you please rebase off last master? I just finished a bunch of changes in regards to file transfers so some new strings were added as well.

**Comment by ghost** [comment]
ok I will
thanks

**Comment by almindor** [comment]
Hey sorry I did a few more small changes in the translatable texts. These should now be final if you could update again.

Thank you!

**Comment by ghost** [comment]
Thank you very much @almindor  for fix this.

**Pull request merged**
