### PR TITLE
Update harbour-jtox-sv.ts

### PR DESCRIPTION
**Pull request by eson57**

### CODE REVIEW

**Comment by almindor** [comment]
I won't merge yet as more changes are coming for the 1.0.1 release. I'll ping you here once they're done so you can update all in one :)

**Comment by eson57** [comment]
Thanks! That makes sence.

**Comment by almindor** [comment]
We should be good now for 1.0.1 (or 1.0.2 since I already pushed 1.0.1 to stores)

**Comment by eson57** [comment]
Great! Here it is.  :+1:

**Comment by almindor** [comment]
Hey, could you please post your nickname or name here as you'd like it to appear in credits please? I'll be adding translators to credits in next release.

**Comment by eson57** [comment]
Of course! My name is Åke Engelbrektson or "eson". Your choice. :)

**Pull request merged**
