### PR TITLE
Update harbour-jtox-es.ts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by almindor** [comment]
Thank you

**Comment by ghost** [comment]
toxcore   v0.2.4 It is already, jTox still is in version v0.2.2. | I just let you know to keep tracking toxcore version.
thanks

**Comment by ghost** [comment]
new version toxcore is released v0.2.5

**Comment by ghost** [comment]
new version toxcore is released v0.2.7

**Pull request merged**
